"""API request/response models."""
from typing import Optional, List
from pydantic import BaseModel, Field


class UserProfile(BaseModel):
    """Collected by the Eligibility Profiler agent (or the frontend form)."""
    state: str = Field(..., examples=["Telangana"])
    annual_income: int = Field(..., description="Family annual income in INR", examples=[180000])
    family_size: int = Field(1, examples=[4])
    has_ration_card: bool = False
    ration_card_type: Optional[str] = Field(None, examples=["White / BPL"])
    existing_insurance: Optional[str] = Field(None, examples=["None"])
    ailment: Optional[str] = Field(None, examples=["Cardiac surgery"])
    language: str = Field("en", description="ISO code for voice guidance", examples=["te", "hi", "en"])
    latitude: Optional[float] = None
    longitude: Optional[float] = None


class AnalyzeRequest(BaseModel):
    profile: UserProfile
    bill_text: Optional[str] = Field(
        None, description="Extracted hospital bill/estimate text (frontend or Bill parser)."
    )


class MatchedScheme(BaseModel):
    name: str
    authority: str
    coverage_amount: Optional[str] = None
    why_eligible: str


class Hospital(BaseModel):
    name: str
    address: str
    distance_note: Optional[str] = None


class AnalyzeResponse(BaseModel):
    matched_schemes: List[MatchedScheme] = []
    coverage_summary: str = ""
    nearby_hospitals: List[Hospital] = []
    document_checklist: List[str] = []
    voice_guidance: str = ""
    disclaimer: str = (
        "This is informational guidance generated by AI. Final eligibility and "
        "coverage must be confirmed with the official scheme portal or an "
        "empanelled hospital before relying on it."
    )
    raw_report: Optional[str] = None
